# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"

	config.ssh.insert_key = false

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "main.yml"
		ansible.vault_password_file = "~/.ansible/vault_pass"
	end
end
